# Site settings
title: AssoB.it
email: your-email@domain.com
name: "Sito AssoB.it"
description: > # this means to ignore newlines until "baseurl:"
  Sito dell'Associazione AssoB.it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.assob.it" # the base hostname & protocol for your site
author: "AssoB.it"
excerpt_separator: "<!-- more -->"
twitter_username: jekyllrb
github_username:  jekyll
github: "http://github.com/assobit/assobit.github.io"
gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
paginate: 3
paginate_path: "/news/page:num/"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      img: "/img/chain-257492_1280.jpg"


# Build settings
markdown: kramdown
