# Site settings
title: AssoB.it
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://assobit.github.io/" # the base hostname & protocol for your site
author: "AssoB.it"
excerpt_separator: ""
twitter_username: jekyllrb
github_username:  jekyll
github: "http://github.com/assobit/assobit.github.io"
paginate: 3
paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
